### ISSUE TITLE
Do not deploy `bin/console`

### ISSUE THREAD

**Issue by jubianchi** [hoaproject/Contributions-Symfony-ConsoleBridge#12]
THe file `bin/console` is only used for test purpose: it should not be part of the delivered code. We should remove the `bin-dir` configuration from the `composer.json` file so that the file is not deployed when users require this library

**Comment by jubianchi** [comment]
@mickaelandrieu thanks but I don't think we should spend too much time on this one: to me, this file will only be really required when working on the library itself. It will be rarely used in other context, I think.

What I propose is simple to drop this file. This will never get linked in top-level package/applications bin directory.
The name of the binary is also too generic. It could easily create conflict with something else.

I'm also thinking of removing much more from dist. archives using a `.gitattributes` (exclude `bin/console`, tests, `.travis.yml`, ...).

Thoughts @hoaproject/hoackers ?

**Comment by Hywan** [comment]
@jubianchi :+1: for dropping it. However, how to test then?

**Comment by jubianchi** [comment]
@Hywan the file will not be drpped just ignored from a composer/dist point of view.

**Comment by Hywan** [comment]
@jubianchi Yup, realized this after.
